name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Use pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: "latest"

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
