name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node

    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: "latest"

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
